/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.maintenance.jsonc --env-file=.dev.vars.maintenance.example --include-runtime=false --env-interface=MaintenanceEnv worker-maintenance-configuration.d.ts` (hash: 8139c6251cb52a0dba717b73af83254b)
interface __BaseEnv_MaintenanceEnv {
	FILES: R2Bucket;
	HYPERDRIVE: Hyperdrive;
	APP_ENV: "staging" | "production" | "local";
	SUPABASE_URL: "https://STAGING_PROJECT_REF.supabase.co" | "https://PRODUCTION_PROJECT_REF.supabase.co" | "https://PROJECT_REF.supabase.co";
	SUPABASE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/maintenance-worker");
	}
	interface StagingEnv {
		FILES: R2Bucket;
		HYPERDRIVE: Hyperdrive;
		APP_ENV: "staging";
		SUPABASE_URL: "https://STAGING_PROJECT_REF.supabase.co";
		SUPABASE_SECRET_KEY: string;
	}
	interface ProductionEnv {
		FILES: R2Bucket;
		HYPERDRIVE: Hyperdrive;
		APP_ENV: "production";
		SUPABASE_URL: "https://PRODUCTION_PROJECT_REF.supabase.co";
		SUPABASE_SECRET_KEY: string;
	}
	interface Env extends __BaseEnv_MaintenanceEnv {}
}
interface MaintenanceEnv extends __BaseEnv_MaintenanceEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "SUPABASE_URL" | "SUPABASE_SECRET_KEY">> {}
}
