/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.cost-guard.jsonc --env-file=.dev.vars.cost-guard.example --include-runtime=false --env-interface=CostGuardEnv worker-cost-guard-configuration.d.ts` (hash: eb1405609ff0484e57dabda961e229a2)
interface __BaseEnv_CostGuardEnv {
	STATE: R2Bucket;
	ALERT_EMAIL: SendEmail;
	APP_ENV: "staging" | "production" | "local";
	CLOUDFLARE_ACCOUNT_ID: "00000000000000000000000000000000";
	BILLING_CYCLE_ANCHOR_DAY_UTC: "30";
	WORKERS_REQUEST_GUARD_LIMIT: "1350000";
	WORKERS_INCLUDED_CPU_MS: "30000000";
	R2_INCLUDED_CLASS_A_OPERATIONS: "1000000";
	R2_INCLUDED_CLASS_B_OPERATIONS: "10000000";
	R2_INCLUDED_STORAGE_BYTES: "10000000000";
	PROTECTED_CUSTOM_DOMAINS: "[{\"hostname\":\"api-staging.meoing.com\",\"service\":\"meoing-api-staging\"}]" | "[{\"hostname\":\"api-staging.meoing.com\",\"service\":\"meoing-api-staging\"},{\"hostname\":\"api.meoing.com\",\"service\":\"meoing-api-production\"}]" | "[{\"hostname\":\"api.local.meoing.invalid\",\"service\":\"meoing-api\"}]";
	ALERT_FROM: "no-reply@auth.meoing.com";
	CLOUDFLARE_COST_GUARD_TOKEN: string;
	ALERT_RECIPIENT: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/cost-guard-worker");
	}
	interface StagingEnv {
		STATE: R2Bucket;
		ALERT_EMAIL: SendEmail;
		APP_ENV: "staging";
		CLOUDFLARE_ACCOUNT_ID: "00000000000000000000000000000000";
		BILLING_CYCLE_ANCHOR_DAY_UTC: "30";
		WORKERS_REQUEST_GUARD_LIMIT: "1350000";
		WORKERS_INCLUDED_CPU_MS: "30000000";
		R2_INCLUDED_CLASS_A_OPERATIONS: "1000000";
		R2_INCLUDED_CLASS_B_OPERATIONS: "10000000";
		R2_INCLUDED_STORAGE_BYTES: "10000000000";
		PROTECTED_CUSTOM_DOMAINS: "[{\"hostname\":\"api-staging.meoing.com\",\"service\":\"meoing-api-staging\"}]";
		ALERT_FROM: "no-reply@auth.meoing.com";
		CLOUDFLARE_COST_GUARD_TOKEN: string;
		ALERT_RECIPIENT: string;
	}
	interface ProductionEnv {
		STATE: R2Bucket;
		ALERT_EMAIL: SendEmail;
		APP_ENV: "production";
		CLOUDFLARE_ACCOUNT_ID: "00000000000000000000000000000000";
		BILLING_CYCLE_ANCHOR_DAY_UTC: "30";
		WORKERS_REQUEST_GUARD_LIMIT: "1350000";
		WORKERS_INCLUDED_CPU_MS: "30000000";
		R2_INCLUDED_CLASS_A_OPERATIONS: "1000000";
		R2_INCLUDED_CLASS_B_OPERATIONS: "10000000";
		R2_INCLUDED_STORAGE_BYTES: "10000000000";
		PROTECTED_CUSTOM_DOMAINS: "[{\"hostname\":\"api-staging.meoing.com\",\"service\":\"meoing-api-staging\"},{\"hostname\":\"api.meoing.com\",\"service\":\"meoing-api-production\"}]";
		ALERT_FROM: "no-reply@auth.meoing.com";
		CLOUDFLARE_COST_GUARD_TOKEN: string;
		ALERT_RECIPIENT: string;
	}
	interface Env extends __BaseEnv_CostGuardEnv {}
}
interface CostGuardEnv extends __BaseEnv_CostGuardEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_ENV" | "CLOUDFLARE_ACCOUNT_ID" | "BILLING_CYCLE_ANCHOR_DAY_UTC" | "WORKERS_REQUEST_GUARD_LIMIT" | "WORKERS_INCLUDED_CPU_MS" | "R2_INCLUDED_CLASS_A_OPERATIONS" | "R2_INCLUDED_CLASS_B_OPERATIONS" | "R2_INCLUDED_STORAGE_BYTES" | "PROTECTED_CUSTOM_DOMAINS" | "ALERT_FROM" | "CLOUDFLARE_COST_GUARD_TOKEN" | "ALERT_RECIPIENT">> {}
}
