import type { LearningProfile, Lesson } from "./types";

export function createLocalPreviewLesson(unitId: string, unitName: string, profile: LearningProfile): Lesson {
  void unitName;
  void profile;
  const prefix = `${unitId}-preview`;
  return {
    schemaVersion: 1,
    id: `${prefix}-lesson`,
    unitId,
    title: "Player demo: English daily routine",
    summary: "Fixed English sample content for testing the lesson player, retries, and speaking controls. It is not generated from the active unit.",
    targetLanguage: "English",
    level: "elementary",
    objectives: [
      "Recognize phrases that introduce steps in a daily routine.",
      "Arrange sentences in a natural order.",
      "Produce short spoken and written responses.",
    ],
    theory: [
      {
        id: `${prefix}-theory-sequence`,
        kind: "grammar",
        title: "Sequence words",
        body: "Use first, then, after that, and finally to make a routine easy to follow. Put the time phrase before or after the main clause consistently.",
      },
      {
        id: `${prefix}-theory-frequency`,
        kind: "concept",
        title: "Frequency and habits",
        body: "Words such as usually, often, sometimes, and never describe how regularly an action happens. In English they normally appear before a main verb but after be.",
      },
      {
        id: `${prefix}-theory-speaking`,
        kind: "pronunciation",
        title: "Speaking in chunks",
        body: "Pause between meaning groups, not between every word: First / I make coffee / and then I review my notes.",
      },
    ],
    examples: [
      { id: `${prefix}-example-1`, source: "I usually get up at seven.", note: "Usually marks a repeated habit." },
      { id: `${prefix}-example-2`, source: "After that, I walk to the station.", note: "After that links two steps." },
      { id: `${prefix}-example-3`, source: "Finally, I plan the next day.", note: "Finally introduces the last step." },
    ],
    glossary: [
      { term: "usually", meaning: "on most occasions", example: "I usually study after dinner." },
      { term: "commute", meaning: "travel regularly between home and work or school" },
      { term: "after that", meaning: "following the previous step" },
      { term: "wind down", meaning: "gradually relax near the end of the day" },
    ],
    sourceReferences: [{ id: `${prefix}-source`, kind: "note", title: "Built-in player demo content" }],
    questions: [
      {
        id: `${prefix}-q1`,
        type: "singleChoice",
        evaluationMode: "local",
        prompt: "Which sentence describes a regular habit?",
        options: [
          { id: "habit", label: "I usually get up at seven." },
          { id: "past", label: "I got up late yesterday." },
          { id: "future", label: "I will get up early tomorrow." },
        ],
        correctOptionId: "habit",
        explanation: "‘Usually’ marks a repeated habit.",
        hint: "Look for an adverb of frequency.",
      },
      {
        id: `${prefix}-q2`,
        type: "multipleChoice",
        evaluationMode: "local",
        prompt: "Choose both natural sequence markers.",
        options: [
          { id: "first", label: "First" },
          { id: "after", label: "After that" },
          { id: "blue", label: "Blue" },
          { id: "although", label: "Although" },
        ],
        correctOptionIds: ["first", "after"],
        explanation: "First and after that explicitly show sequence.",
        hint: "Pick expressions that answer ‘what happens next?’",
      },
      {
        id: `${prefix}-q3`,
        type: "trueFalse",
        evaluationMode: "local",
        prompt: "Decide whether the statement is true.",
        statement: "In ‘I am often tired’, often naturally comes after be.",
        correct: true,
        explanation: "Frequency adverbs generally follow forms of be.",
      },
      {
        id: `${prefix}-q4`,
        type: "fillBlank",
        evaluationMode: "local",
        prompt: "Complete the sentence with a sequence marker.",
        template: "___, I make coffee before I start work.",
        acceptedAnswers: ["First", "First of all"],
        match: { ignorePunctuation: true },
        explanation: "First introduces the opening action in a sequence.",
        hint: "This is the opening step.",
      },
      {
        id: `${prefix}-q5`,
        type: "multiCloze",
        evaluationMode: "local",
        prompt: "Complete both parts of the routine.",
        template: "I ___ up at seven and ___ breakfast at seven thirty.",
        blanks: [
          { id: "wake", acceptedAnswers: ["wake", "get"] },
          { id: "eat", acceptedAnswers: ["eat", "have"] },
        ],
        match: { ignorePunctuation: true },
        explanation: "Wake/get up and eat/have breakfast are common routine collocations.",
        hint: "Use two present-simple verbs.",
      },
      {
        id: `${prefix}-q6`,
        type: "wordBank",
        evaluationMode: "local",
        prompt: "Build a natural sentence.",
        tokens: [
          { id: "i", label: "I" },
          { id: "usually", label: "usually" },
          { id: "walk", label: "walk" },
          { id: "home", label: "home" },
        ],
        correctOrderIds: ["i", "usually", "walk", "home"],
        explanation: "The frequency adverb appears before the main verb.",
        hint: "Subject → frequency → verb → place.",
      },
      {
        id: `${prefix}-q7`,
        type: "matching",
        evaluationMode: "local",
        prompt: "Match each routine phrase with its meaning.",
        pairs: [
          { leftId: "commute", left: "commute to work", rightId: "travel", right: "travel to the workplace" },
          { leftId: "wind", left: "wind down", rightId: "relax", right: "gradually relax" },
          { leftId: "plan", left: "plan ahead", rightId: "prepare", right: "prepare in advance" },
        ],
        explanation: "These phrases describe movement, relaxation, and preparation.",
        hint: "Use the meaning of the main verb in each phrase.",
      },
      {
        id: `${prefix}-q8`,
        type: "reorderDialogue",
        evaluationMode: "local",
        prompt: "Put the short conversation in a natural order.",
        turns: [
          { id: "ask", speaker: "A", label: "What do you do after work?" },
          { id: "answer", speaker: "B", label: "I usually go for a walk." },
          { id: "follow", speaker: "A", label: "That sounds relaxing." },
        ],
        correctOrderIds: ["ask", "answer", "follow"],
        explanation: "A question is followed by its answer and then a reaction.",
        hint: "Find the question first.",
      },
      {
        id: `${prefix}-q9`,
        type: "categorize",
        evaluationMode: "local",
        prompt: "Put each activity in the most likely part of the day.",
        categories: [
          { id: "morning", label: "Morning" },
          { id: "evening", label: "Evening" },
        ],
        items: [
          { id: "breakfast", label: "have breakfast", categoryId: "morning" },
          { id: "alarm", label: "turn off the alarm", categoryId: "morning" },
          { id: "wind-down", label: "wind down", categoryId: "evening" },
          { id: "next-day", label: "plan the next day", categoryId: "evening" },
        ],
        explanation: "Breakfast and alarms are morning cues; winding down and next-day planning are evening cues.",
        hint: "Think about when the activity normally happens.",
      },
      {
        id: `${prefix}-q10`,
        type: "translation",
        evaluationMode: "ai",
        prompt: "Translate naturally into English.",
        sourceText: "Después de eso, camino a la estación.",
        targetLanguage: "English",
        referenceAnswer: "After that, I walk to the station.",
        rubric: ["Preserve the sequence marker", "Use the present simple", "Use a natural destination phrase"],
        explanation: "A natural answer uses after that and the present simple.",
        hint: "Start with a sequence marker.",
      },
      {
        id: `${prefix}-q11`,
        type: "errorCorrection",
        evaluationMode: "local",
        prompt: "Correct the sentence.",
        incorrectText: "She usually is make coffee at seven.",
        acceptedAnswers: ["She usually makes coffee at seven."],
        match: { ignorePunctuation: true },
        explanation: "Use a third-person present-simple verb; do not add be before make.",
        hint: "Check the verb after she.",
        supplementalHint: "Remove is and add -s to make.",
      },
      {
        id: `${prefix}-q12`,
        type: "dictation",
        evaluationMode: "local",
        prompt: "Type the sentence you hear or read from the fallback transcript.",
        transcript: "Finally, I plan the next day.",
        acceptedAnswers: ["Finally, I plan the next day."],
        match: { ignorePunctuation: true },
        explanation: "The sentence closes the sequence with finally.",
        hint: "The first word signals the last step.",
      },
      {
        id: `${prefix}-q13`,
        type: "freeWriting",
        evaluationMode: "ai",
        prompt: "Write 35–80 words about your weekday routine. Use at least three sequence markers.",
        minWords: 35,
        maxWords: 80,
        rubric: ["Task completion", "Sequence markers", "Present-simple accuracy", "Clarity"],
        explanation: "A clear paragraph uses a logical sequence and consistent tense.",
        hint: "Plan four steps before you write.",
      },
      {
        id: `${prefix}-q14`,
        type: "speakingRepeat",
        evaluationMode: "ai",
        prompt: "Record yourself repeating the sentence in meaning chunks.",
        modelText: "First, I make coffee, and then I review my notes.",
        rubric: ["Intelligibility", "Rhythm", "Pausing", "Fluency"],
        explanation: "Meaningful pauses make the sentence easier to understand.",
        hint: "Pause after first and coffee.",
      },
      {
        id: `${prefix}-q15`,
        type: "speakingRoleplay",
        evaluationMode: "ai",
        prompt: "Respond as if you are talking to a new classmate.",
        role: "A learner describing a weekday",
        scenario: "A classmate asks what you normally do before work or school.",
        goal: "Give at least three ordered actions and ask one follow-up question.",
        rubric: ["Task completion", "Fluency", "Grammar", "Interaction"],
        explanation: "A good response gives ordered details and keeps the exchange moving.",
        hint: "Use first, then, and after that.",
        supplementalHint: "Finish with ‘What about you?’",
      },
    ],
    createdAt: new Date().toISOString(),
  };
}
